Argument default value should be undefined
graphql-python/graphene pull request #1300
Opened 2021-01-06 14:17 UTC by wakemaster39

resolves #1195

This stops `null` from being populated in the introspection query as mentioned in #1195. This also solves the problem of `None` being passed into the kwargs of a `mutate` call if no value was passed in by the end user.

2021-01-06 19:08 UTC, wakemaster39 commented
I am unsure which of the two options you want me to do to fix the unit tests.

1, set default values for the failing tests to be None.
2, remove the no longer passed in values from the assertion statements.

2021-01-28 13:48 UTC, DonQueso89 commented
> I am unsure which of the two options you want me to do to fix the unit tests.
> 
> 1, set default values for the failing tests to be None.
> 2, remove the no longer passed in values from the assertion statements.

thumbs up for this PR! 

I would say remove the no longer passed in values from the assertion right? We're testing whether the value is absent if its not passed in

2021-02-17 05:49 UTC, zbyte64 requested changes
See the commit to fix the test.

2021-02-17 05:49 UTC, zbyte64 commented on graphene/types/argument.py
> +        assert arg_name not in arguments, f'More than one Argument have same name "{arg_name}".'
I think this is causing the test to fail. It applies black formatting to the code an fails if the file changes. This is where it cites the changed file: https://travis-ci.org/github/graphql-python/graphene/jobs/753187127#L243

2021-03-01 13:56 UTC, wakemaster39 commented
Ok I finally got around to cleaning up the changes that moving to Undefined makes to the unit tests. This should be good to go now.

2021-03-02 18:45 UTC, zbyte64 approved these changes
:+1:

2021-03-24 01:57 UTC, daynejones approved these changes

2021-06-07 16:05 UTC, lovetoburnswhen commented
+1 this seems like a critical feature

2021-07-05 18:58 UTC, SteinRobert commented
Does this PR need any more work? I'd be happy to help, otherwise I would really appreciate this to make it into the next release 😃

2021-10-05 13:14 UTC, pavelion approved these changes

2022-05-19 02:18 UTC, frankchen211 commented
any update?

2022-06-07 20:33 UTC, artemijan commented
I believe the best way is just fork this repo, right? I need to differentiate null values with not provided in my app. This thread is about 1 year

2022-06-08 06:03 UTC, SteinRobert commented
@Cito @jkimbo you guys probably have a lot of work on your hands, thank you so much for caring about the project!
Just wanted to check in whether this change is something you consider accepting or if it needs any more work. I'd surely help making any more changes if needed.

2022-08-13 13:00 UTC, erikwrede commented
Hey everyone, will check this out in detail later. 
This might be a breaking change (breaking the changes from v2-> v3), but I believe releasing a new minor version for this will be sufficient.

2022-08-13 13:06 UTC, closed without merging