Complete deprecated fields and arguments support
graphql-python/graphene pull request #1472
Opened 2022-11-12 13:15 UTC by vhutov

**Implementing enhancement from #1446**
In this PR I ensure that `Argument`, `Field` and `InputField` support **deprecation** functionality.

TODOs from the issue:

- [x]  Is this already supported in graphql-core?
- [x] Add deprecation reason field to Meta Options Classes and [Input]Field logic
- [x] Check that required NonNull input fields are not deprecatable (see spec)

Notes:
1. `Field` and `InputField` already had this field, whereas `Argument` didn't.
2. I added the `deprecation_reason` field to the `InputObject` Meta, but turns out that those options were not populating when mounting. So I updated the mounting code.
3. When mounting I added a check if the unmounted type is `InputObject`. I tried making it more generic and using the `SubclassWithMeta`, but then lots of tests start failing, because Scalars have descriptions different from those in checks, so I decided to leave only the `InputObject`.
4. `ObjectType` is not implicitly mountable. From the doc: "ObjectType must be mounted using ``graphene.Field``." So I didn't update Meta options as they won't be used when mounting.
5. When constructing schema, some objects were already passing deprecation reason. I added the missing parts: `InputField` and `Argument`. `Enum` and `Field` were compliant.

2022-11-12 14:16 UTC, erikwrede commented
That was fast! Thank you for the PR :) I'll check it out ASAP!

2022-11-13 00:19 UTC, vhutov commented
@erikwrede I felt some courage to play with `MountedType` and `SubclassWithMeta` support. Now it's generic and works with `Enum`'s, `InputObject`'s and `Scalar`'s. I added a class method which describes which Meta fields to inherit. I think it's clear to a reader what to expect. LMKWYT

2022-11-16 12:08 UTC, vhutov commented
@erikwrede Hey! Have you had a chance to take a look?

2022-11-16 12:23 UTC, erikwrede commented
@vhutov Sorry for taking to long, I was actually just looking at your new changes right now. 
Need to play around with it to give you a more thorough opinion though, as this is had become a larger change than just adding the deprecation now. Trying to get back to you on the weekend 🙂

2022-11-16 14:14 UTC, vhutov commented
@erikwrede no worries, I'm not in rush. I just thought it'd be better to add Meta support as well. I can certainly split them in two, if you think it's better. Thanks for looking at this!

2022-11-21 14:25 UTC, erikwrede commented
Having thought about it again, think it's better to split up the two PRs and think about the `mountable_meta` again. The current proposal would  also require users to adapt the new `mountable_meta` classmethod,  potentially breaking things by requiring them to implement `mountable_meta` for all `kwargs` they want to be inheritable.

If we are talking about a redesign of that part, I'd personally prefer to explicitly get the inheritable fields from a type, without having to implement a second `mountable_meta` method.
That configuration, it would be less redundant and field name changes wouldn't pose an issue if someone forgot to modify the return of `mountable_meta`.

A rough concept could look something like this:

Assume we have a base class (roughly based on the actual `InputTypeOptions` class in Graphene)
```python
class InputObjectTypeOptions:
   description: str
   deprecation_reason: str
   abcd: str
```
we would have an explicit definition of inheritable fields from that class. It is also extendable by subclassing it.

We could now adapt this for mounted types like `Argument`.
If a mounted Type specifies a class `MountedTypeOptions`, we can use that to extract all fields that are contained in the `MountedTypeOptions` from the `UnmountedTypeOptions` **iff** they exist on both types:

```python 
InputObjectType.meta_type = InputObjectTypeOptions
class ArgumentOptions:
   description: str
   deprecation_reason: str
   required: bool



Mount InputObjectType
# Extract deprecation reason from InputObjectTypeOptions (InputObjectType._meta)
# Don't extract required: field not defined on InputObjectTypeOptions
# Don't extract abcd: field not defined on ArgumentOptions
```
 If no `MountedTypeOptions` class exists for the mounted type,  we fall back to the legacy behavior.

This is just an initial idea, and by no means a finalized design. Also open to suggestions on why we should use `mountable_meta` instead. LMKWYT!

2022-11-27 19:34 UTC, vhutov commented
@erikwrede cleaned up the PR to contain only the deprecation reason ✅ 
Let me think about the proposed idea meanwhile.

2022-11-27 19:40 UTC, vhutov commented
**UPD:** Changed PR description

2022-12-06 14:53 UTC, erikwrede requested changes
Review for this was still on my list - thank you for updating the PR!

I noticed that you made changes to `field.py` to only allow deprecation on nullable fields. According to the Spec, this constraint only applies to input fields. 
Look at the following example from spec:

```
type ExampleType {
  invalidField(
    newArg: String
    oldArg: String! @deprecated(reason: "Use `newArg`.")
  ): String
}
```
With input fields, the restriction makes sense, as we don't have any alternative to passing a value to the required `oldField`, although `oldField` is deprecated. For input fields, the alternative is to not query the field anymore.

The rest looks good, thank you!

2022-12-06 14:53 UTC, erikwrede commented on graphene/types/field.py
> +            ), f"Field {name} is required, cannot deprecate it."
This restriction only applies to _input object fields_ & arguments : https://spec.graphql.org/draft/#sec--deprecated

2022-12-06 14:53 UTC, erikwrede commented on graphene/types/tests/test_mutation.py
See field.py

2022-12-10 11:22 UTC, erikwrede approved these changes
LGTM!
As a follow-up, we should rework the `get_introspection_query()` for schema to allow for optional args to be introspected. Currently `schema.introspect()` calls this using the default args that set `input_value_deprecation: bool = False,`, excluding any deprecated fields or args.

2022-12-10 11:25 UTC, merged

2022-12-10 11:25 UTC, erikwrede commented
Will release tonight in `3.2.1`, thank you! 🙂

2022-12-10 23:37 UTC, vhutov commented
Thanks!

2025-06-12 06:37 UTC, kashifalikhan36 commented
That's impressive