types: add option for strict connection types
graphql-python/graphene pull request #1504
Opened 2023-05-04 21:05 UTC by shrouxm

This PR adds a `strict_types` meta option to the relay `Connection` class to simplify the use case identified in this issue: https://github.com/graphql-python/graphene-django/issues/901

Default of `False` is the old behavior, and when set to `True` generated `TConnection` types will be typed as `edges: [TEdge!]!` instead of `edges: [TEdge]!` and `TEdge` will have `node: T!` instead of `node: T`.

This avoids duplicating logic and string descriptions for subclasses which just want to implement this common behavior. If this behavior is deemed desirable by default it would be trivial to flip the flag's default or remove it entirely. It only make the types stricter so it oughtn't break any existing code (though it will cause unexpected changes to user's schema's nonetheless, which is why I kept the default to `False`).

2023-06-04 21:02 UTC, erikwrede requested changes
Thanks for the PR! Can you please add some test cases for this, testing the schema generation? 😊

2023-06-08 22:33 UTC, shrouxm commented
@erikwrede does that look like what you meant?

2023-07-25 19:12 UTC, shrouxm commented
@erikwrede it looks like the checks will never complete because the python 3.6 test workflow no longer exists after https://github.com/graphql-python/graphene/pull/1507/files but the GitHub repo settings still require that workflow to run

2023-07-26 06:25 UTC, erikwrede approved these changes

2023-07-26 06:25 UTC, merged